name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Vue 3 frontend
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rensvelden/albumrater-adminpanel:latest
        
    - name: Log out from Dockerhub
      run: docker logout https://hub.docker.com/
